use_frameworks!

platform :ios, '12.0'

# pod 'Bitcoin', :path => '../../Bitcoin'

target 'AirgappedSigning_Example' do
  pod 'AirgappedSigning', :path => '../'

  target 'AirgappedSigning_Tests' do
    inherit! :search_paths
  end
end
